### ISSUE TITLE
Request: Implementation of Login Page for Survey Form

### ISSUE THREAD

**Issue by Nitish0589** [Nitish0589/SCM-FINAL-EVALUATION#2]
Hello Novesh,

This issue is raised to request the implementation of a login page for our survey form. The login page is essential for ensuring user authentication and data security. Contributors are invited to collaborate on this task, adhering to established coding standards and considering factors such as usability, accessibility, and security.

Deadline:- 8th of May, 2024

**Comment by Noveshsharma7777** [comment]
ok, I will get to you as soon as possible.

**Comment by Noveshsharma7777** [comment]
I have pushed the login page. you can check it out now

**Comment by Nitish0589** [comment]
Good job done.
