### ISSUE TITLE
Request: Implementation of Login Page for Survey Form

### ISSUE THREAD

**Issue by Nitish0589** [Nitish0589/SCM-FINAL-EVALUATION#4]
Hello Onik,

This issue is raised to request the implementation of a contact us page for our survey form. Contributors are invited to collaborate on this task, adhering to established coding standards and considering factors such as usability, accessibility, and security.

Deadline:- 9th of May, 2024

**Comment by onikchugh01** [comment]
Created the page. You can reveiw it now.

**Comment by Nitish0589** [comment]
Good job done
