### ISSUE TITLE
Request: Implementation of Thank You Page for Survey Form

### ISSUE THREAD

**Issue by Nitish0589** [Nitish0589/SCM-FINAL-EVALUATION#9]
Hello Novesh,

This issue is raised to request the implementation of a Thank You page for our survey form. We require you to link this page to the page 2 of our You are invited to collaborate on this task, adhering to established coding standards and considering factors such as usability, accessibility, and security.

Deadline:- 15th of May, 2024

**Comment by Noveshsharma7777** [comment]
Done
